  build:
    name: Build Artifact
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    defaults:
      run:
        working-directory: node-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Prepare results folder
        run: mkdir -p all-test-results

      - name: Download Node 16 test results
        uses: actions/download-artifact@v4
        with:
          name: test-results-16
          path: all-test-results/16

      - name: Download Node 18 test results
        uses: actions/download-artifact@v4
        with:
          name: test-results-18
          path: all-test-results/18

      - name: Download Node 20 test results
        uses: actions/download-artifact@v4
        with:
          name: test-results-20
          path: all-test-results/20

      - name: Summarize test results
        run: |
          mkdir -p dist
          echo "===== TEST SUMMARY =====" > dist/summary.txt
          find all-test-results -type f -name "results.txt" -exec cat {} \; >> dist/summary.txt
          cat dist/summary.txt

      - name: Build project
        run: |
          mkdir -p dist
          cp server.js dist/
          cp package.json dist/
          echo "Build created at $(date)" >> dist/build-info.txt

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-dist
          path: node-backend/dist/
