name: Node.js CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - "**"

jobs:
  # 1️⃣ CI job
  ci:
    name: CI (Lint + Test)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: node-backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint --if-present

      - name: Run tests
        run: npm test --if-present

      - name: Archive test results
        if: always()
        run: |
          mkdir -p test-results
          echo "dummy test results" > test-results/results.txt

      - name: Upload test artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: node-backend/test-results/

  # 2️⃣ Deploy QA (when pushing to dev)
  deploy_qa:
    name: Deploy QA
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/dev'
    concurrency:
      group: deploy-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: test-results
          path: ./test-results

      - name: Run QA deploy script
        run: |
          chmod +x ./run.sh
          ./run.sh qa

  # 3️⃣ Deploy Production (when pushing to main)
  deploy_prod:
    name: Deploy Production
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main'
    concurrency:
      group: deploy-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: test-results
          path: ./test-results

      - name: Run Production deploy script
        run: |
          chmod +x ./run.sh
          ./run.sh prod
